language: node_js
node_js:
- 10

branches:
  only:
  - master

script:
- npm install
- gulp build --verbose
- npm run test

cache:
  npm: true
  directories:
  - ~/.cache

env:
  global:
  - MOZ_HEADLESS=1
addons:
  firefox: latest