language: node_js
node_js:
- "8.10.0"

branches:
  only:
  - master

before_install:
- npm install gulp -g

script:
- npm install
- gulp build --verbose
- npm run test

cache:
  directories:
  - node_modules